name: Testing
on: push
jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cc: /usr/bin/gcc
            cxx: /usr/bin/g++
            cxx_standard: 20
          - cc: /usr/bin/gcc
            cxx: /usr/bin/g++
            cxx_standard: 17
          - cc: /usr/bin/gcc
            cxx: /usr/bin/g++
            cxx_standard: 14
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      CXX_STANDARD: ${{ matrix.cxx_standard }}
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: bash ${{github.workspace}}/ci/configure.sh
    - name: Build
      run: bash ${{github.workspace}}/ci/build.sh
    - name: Run Tests
      run: bash ${{github.workspace}}/ci/run_test.sh
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - cc: cl.exe
            cxx: cl.exe
            use_vswhere: "ON"
          - cc: clang.exe
            cxx: clang++.exe
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      USE_VSWHERE: ${{ matrix.use_vswhere }}
    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Configure
      shell: pwsh
      run: ${{github.workspace}}/ci/configure.ps1
    - name: Build
      shell: pwsh
      run: ${{github.workspace}}/ci/build.ps1
    - name: Run Tests
      shell: pwsh
      run: ${{github.workspace}}/ci/run_test.ps1
  macOS:
    runs-on: macos-latest
    env:
      CXX_STANDARD: 14
      GENERATOR: Xcode
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: bash ${{github.workspace}}/ci/configure.sh
    - name: Build
      run: bash ${{github.workspace}}/ci/build.sh
    - name: Run Tests
      run: bash ${{github.workspace}}/ci/run_test.sh
