name: CMake
on: push
env:
  BUILD_TYPE: Release
jobs:
  build-clang:
    runs-on: ubuntu-latest
    env:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
      CXX_STANDARD: 20
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_STANDARD=${{env.CXX_STANDARD}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      run: ${{github.workspace}}/build/test
